server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        default_schema: vrt
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: '@db.url@'
      username: '@db.user@'
      password: '@db.password@'
      hikari.maximum-pool-size: 10
    flyway:
      schemas: ps
      url: '@db.url@'
      table: flyway_schema_history

info:
  version: '@project.version@'
  stage: dev

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  retry-attempts: 3
  max-poll-records: 100
  max-poll-interval-ms: 60000
  max-session-timeout-ms: 6000
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    enabled: true
    prefix: vortigon
    concurrency: 7
    throttling-timeout-ms: 1000
  topic:
    party:
      initial: mg-events-party
      max-poll-records: 50

repository:
  url: http://dominant:8022/v1/domain/repository_client
  network-timeout: 5000

service:
  dominant:
    url: http://dominant:8022/v1/domain/repository
    networkTimeout: 5000

scheduler:
  enabled: false
  lockFor: 30m
  pollingDelay: 3000
  querySize: 10
